name: gps-routes

networks:
  default:
  homelab-net:
    external: true

services:
  api-server:
    container_name: api-server
    image: ghcr.io/rm-hull/gps-routes-api:latest
    command:
      - api-server
      - "8080"
    env_file:
      - .env
    environment:
      - OS_NAMES_API_KEY
      - GPS_ROUTES_API_KEY
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SCHEMA
      - POSTGRES_USER
    restart: always
    healthcheck:
      disable: false
    depends_on:
      postgis:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
      import-data:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gps-routes.entrypoints=websecure"
      - "traefik.http.routers.gps-routes.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/gps-routes/`)"
      - "traefik.http.services.gps-routes.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/gps-routes"
      - "dockflare.service=http://api-server:8080"
    networks:
      - default
      - homelab-net

  run-migrations:
    container_name: run-migrations
    image: ghcr.io/rm-hull/gps-routes-api:latest
    command:
      - migration
      - up
      - /data/migrations/
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SCHEMA
      - POSTGRES_USER
    volumes:
      - ./db/migrations:/data/migrations
    restart: "no"
    healthcheck:
      disable: true
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - default

  import-data:
    container_name: import-data
    image: ghcr.io/rm-hull/gps-routes-api:latest
    command:
      - import
      - /data/backup/
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SCHEMA
      - POSTGRES_USER
    volumes:
      - ./data/backup:/data/backup
    restart: "no"
    healthcheck:
      disable: true
    depends_on:
      postgis:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully
    networks:
      - default

  postgis:
    container_name: postgis
    image: ghcr.io/baosystems/postgis:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SCHEMA
      - POSTGRES_USER
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      retries: 5
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - default
      - homelab-net

  postgis-exporter:
    container_name: postgis-exporter
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_URI: "${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
    networks:
      - default
      - homelab-net

