{
 "title": "Gin Gonic & Go Application Metrics",
 "tags": [
  "gin",
  "gonic",
  "go",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(gin_gonic_requests_total, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gin_gonic_requests_total{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Error Rate (4xx & 5xx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(gin_gonic_requests_total{job=~\"$job\", instance=~\"$instance\", path=~\"$path\", code=~\"[45]..\"}[$__rate_interval])) / sum(rate(gin_gonic_requests_total{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval]))) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "99th Percentile Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gin_gonic_request_duration_bucket{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 Latency"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gin_gonic_response_size_bytes_sum{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) / sum(rate(gin_gonic_response_size_bytes_count{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "Avg Response Size"
    }
   ]
  },
  { "title": "Throughput and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests Per Second by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps", "label": "Requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gin_gonic_requests_total{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Latency by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gin_gonic_request_duration_bucket{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) by (le, path))",
     "legendFormat": "p99 - {{path}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_gonic_request_duration_bucket{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) by (le, path))",
     "legendFormat": "p95 - {{path}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gin_gonic_request_duration_bucket{job=~\"$job\", instance=~\"$instance\", path=~\"$path\"}[$__rate_interval])) by (le, path))",
     "legendFormat": "p50 - {{path}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Allocation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "p99 GC Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(go_gc_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "go_info{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}