/*
 * GPS Routes API
 *
 * API to retrieve and search GPS Walking Routes
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Nearby struct {

	// The object ID identifies the GPS route (typically this is the MD5 hash of the route reference)
	ObjectID string `json:"objectID" bson:"objectID"`

	// A human friendly unique identifier for the route.
	Ref string `json:"ref" bson:"ref"`

	// The route title
	Description string `json:"description" bson:"description"`
}
