/*
 * GPS Routes API
 *
 * API to retrieve and search GPS Walking Routes
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SearchRequest struct {

	// Search phrase
	Query string `json:"query"`

	Offset int32 `json:"offset,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	// the bounding box with bottom-left lat/lng, followed by top-right lat/lng
	BoundingBox []float32 `json:"boundingBox,omitempty"`

	// Filtering by facet values
	Facets map[string][]string `json:"facets,omitempty"`
}
