/*
 * GPS Routes API
 *
 * API to retrieve and search GPS Walking Routes
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type RouteMetadata struct {

	// The object ID identifies the GPS route (typically this is the MD5 hash of the route reference)
	ObjectID string `json:"objectID" bson:"objectID"`

	// A human friendly unique identifier for the route.
	Ref string `json:"ref" bson:"ref"`

	// The route title
	Title string `json:"title" bson:"title"`

	// Typically a long passage of text describing aspects of the route
	Description string `json:"description" bson:"description"`

	// The main image URL associated with the route
	HeadlineImageUrl string `json:"headline_image_url" bson:"headline_image_url"`

	StartPosition GeoLoc `json:"_geoloc,omitempty" bson:"_geoloc,omitempty"`

	// The time the route was generated.
	CreatedAt time.Time `json:"created_at" bson:"created_at"`

	Nearby []Nearby `json:"nearby,omitempty" bson:"nearby,omitempty"`

	// URL pointing to the associated GPX route data
	GpxUrl string `json:"gpx_url,omitempty" bson:"gpx_url,omitempty"`

	Images []Image `json:"images,omitempty" bson:"images,omitempty"`

	// A rough distance indicating the length of the route
	DistanceKm float64 `json:"distance_km,omitempty" bson:"distance_km,omitempty"`

	// A link to a (YouTube) video associated with the route
	VideoUrl *string `json:"video_url,omitempty" bson:"video_url,omitempty"`

	// Where exists, a nearby postcode
	Postcode *string `json:"postcode,omitempty" bson:"postcode,omitempty"`

	// The district in which the route starts
	District *string `json:"district,omitempty" bson:"district,omitempty"`

	// The county in which the route starts
	County *string `json:"county,omitempty" bson:"county,omitempty"`

	// The region in which the route starts
	Region *string `json:"region,omitempty" bson:"region,omitempty"`

	// The country in which the route starts
	Country *string `json:"country,omitempty" bson:"country,omitempty"`
}
