/*
 * GPS Routes API
 *
 * API to retrieve and search GPS Walking Routes
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GeoLoc - A pair of lat/lng co-ordinates (WSG84) typically indicating the start point of the route
type GeoLoc struct {

	// Latitude
	Lat float32 `json:"lat"`

	// Longitude
	Lng float32 `json:"lng"`
}
