/*
 * GPS Routes API
 *
 * API to retrieve and search GPS Walking Routes
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GeoJson - A GeoJSON object
type GeoJson struct {

	// GeoJSON type
	Type string `json:"type"`

	// Longitude, Latitude
	Coordinates []float64 `json:"coordinates"`
}
